---

x-base: &base
  image: ${registry}${testnet}:latest
  restart: on-failure
  build:
    context: "../../"
    dockerfile: "Dockerfile.source"
    args:
      CARDANO_NODE_REF: "karknu/10_1_4_anthithesis_blockfetch_bugs"

x-env: &env
  POOL_ID: "0" # Placeholder required for override

services:
  p1:
    <<: *base
    container_name: p1
    hostname: p1.example
    volumes:
      - p1:/opt/cardano-node/data
    ports:
      - "3001:3001"
    environment:
      <<: *env
      POOL_ID: "1"

  p2:
    <<: *base
    container_name: p2
    hostname: p2.example
    volumes:
      - p2:/opt/cardano-node/data
    ports:
      - "3002:3001"
    environment:
      <<: *env
      POOL_ID: "2"

  p3:
    <<: *base
    container_name: p3
    hostname: p3.example
    volumes:
      - p3:/opt/cardano-node/data
    ports:
      - "3003:3001"
    environment:
      <<: *env
      POOL_ID: "3"

  p4:
    <<: *base
    container_name: p4
    hostname: p4.example
    volumes:
      - p4:/opt/cardano-node/data
    ports:
      - "3004:3001"
    environment:
      <<: *env
      POOL_ID: "4"

  p5:
    <<: *base
    container_name: p5
    hostname: p5.example
    volumes:
      - p5:/opt/cardano-node/data
    ports:
      - "3005:3001"
    environment:
      <<: *env
      POOL_ID: "5"

  p6:
    <<: *base
    container_name: p6
    hostname: p6.example
    volumes:
      - p6:/opt/cardano-node/data
    ports:
      - "3006:3001"
    environment:
      <<: *env
      POOL_ID: "6"

  p7:
    <<: *base
    container_name: p7
    hostname: p7.example
    volumes:
      - p7:/opt/cardano-node/data
    ports:
      - "3007:3001"
    environment:
      <<: *env
      POOL_ID: "7"

  p8:
    <<: *base
    container_name: p8
    hostname: p8.example
    volumes:
      - p8:/opt/cardano-node/data
    ports:
      - "3008:3001"
    environment:
      <<: *env
      POOL_ID: "8"

  p9:
    <<: *base
    container_name: p9
    hostname: p9.example
    volumes:
      - p9:/opt/cardano-node/data
    ports:
      - "3009:3001"
    environment:
      <<: *env
      POOL_ID: "9"

  p10:
    <<: *base
    container_name: p10
    hostname: p10.example
    volumes:
      - p10:/opt/cardano-node/data
    ports:
      - "3010:3001"
    environment:
      <<: *env
      POOL_ID: "10"

  p11:
    <<: *base
    container_name: p11
    hostname: p11.example
    volumes:
      - p11:/opt/cardano-node/data
    ports:
      - "3011:3001"
    environment:
      <<: *env
      POOL_ID: "11"

  p12:
    <<: *base
    container_name: p12
    hostname: p12.example
    volumes:
      - p12:/opt/cardano-node/data
    ports:
      - "3012:3001"
    environment:
      <<: *env
      POOL_ID: "12"

  s1:
    image: ${registry}${testnet}_sidecar:latest
    restart: on-failure
    container_name: s1
    hostname: s1.example
    environment:
      POOLS: "12"

volumes:
  p1:
  p2:
  p3:
  p4:
  p5:
  p6:
  p7:
  p8:
  p9:
  p10:
  p11:
  p12:
