---

x-base: &base
  image: us-central1-docker.pkg.dev/molten-verve-216720/cardano-repository/livio_10.1.4-p3:latest
  restart: on-failure
  build:
    context: "../../"
    dockerfile: "Dockerfile.compiled"
    args:
      CARDANO_NODE_VERSION: "10.1.4"

x-env: &env
  POOL_ID: "0" # Placeholder required for override

services:
  p1:
    <<: *base
    container_name: p1
    hostname: p1.example
    volumes:
      - p1:/opt/cardano-node/data
    ports:
      - "3001:3001"
    environment:
      <<: *env
      POOL_ID: "1"
      PEER_SHARING: "false"

  p2:
    <<: *base
    container_name: p2
    hostname: p2.example
    volumes:
      - p2:/opt/cardano-node/data
    ports:
      - "3002:3001"
    environment:
      <<: *env
      POOL_ID: "2"

  p3:
    <<: *base
    container_name: p3
    hostname: p3.example
    volumes:
      - p3:/opt/cardano-node/data
    ports:
      - "3003:3001"
    environment:
      <<: *env
      POOL_ID: "3"
      PEER_SHARING: "false"

volumes:
  p1:
  p2:
  p3:
